//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital.caliber.services.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("digital.caliber.services.Resources.Texts.TextsResource", typeof(TextsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolton Anterior.
        /// </summary>
        internal static string Bolton_Antero {
            get {
                return ResourceManager.GetString("Bolton_Antero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolton.
        /// </summary>
        internal static string Bolton_Title {
            get {
                return ResourceManager.GetString("Bolton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolton Total.
        /// </summary>
        internal static string Bolton_Total {
            get {
                return ResourceManager.GetString("Bolton_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antero Superior.
        /// </summary>
        internal static string DentalBone_HigherAntero {
            get {
                return ResourceManager.GetString("DentalBone_HigherAntero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antero Inferior.
        /// </summary>
        internal static string DentalBone_LowerAntero {
            get {
                return ResourceManager.GetString("DentalBone_LowerAntero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incisivos Inferiores.
        /// </summary>
        internal static string DentalBone_LowerIncisives {
            get {
                return ResourceManager.GetString("DentalBone_LowerIncisives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancia Oseo-Dentaria.
        /// </summary>
        internal static string DentalBone_Title {
            get {
                return ResourceManager.GetString("DentalBone_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior.
        /// </summary>
        internal static string Higher {
            get {
                return ResourceManager.GetString("Higher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceso Superior.
        /// </summary>
        internal static string HigherExcess {
            get {
                return ResourceManager.GetString("HigherExcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior Izquierdo.
        /// </summary>
        internal static string HigherLeft {
            get {
                return ResourceManager.GetString("HigherLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior Derecho.
        /// </summary>
        internal static string HigherRigth {
            get {
                return ResourceManager.GetString("HigherRigth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inferior.
        /// </summary>
        internal static string Lower {
            get {
                return ResourceManager.GetString("Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceso Inferior.
        /// </summary>
        internal static string LowerExcess {
            get {
                return ResourceManager.GetString("LowerExcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inferior izquierdo.
        /// </summary>
        internal static string LowerLeft {
            get {
                return ResourceManager.GetString("LowerLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inferior Derecho.
        /// </summary>
        internal static string LowerRigth {
            get {
                return ResourceManager.GetString("LowerRigth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moyers (Predicción de discrepancia).
        /// </summary>
        internal static string Moyers_Title {
            get {
                return ResourceManager.GetString("Moyers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string Patient_Date {
            get {
                return ResourceManager.GetString("Patient_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de H.C..
        /// </summary>
        internal static string Patient_HcNumber {
            get {
                return ResourceManager.GetString("Patient_HcNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente.
        /// </summary>
        internal static string Patient_Name {
            get {
                return ResourceManager.GetString("Patient_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesional.
        /// </summary>
        internal static string Patient_Professional {
            get {
                return ResourceManager.GetString("Patient_Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información del Paciente.
        /// </summary>
        internal static string Patient_Title {
            get {
                return ResourceManager.GetString("Patient_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Haenggi Mediciones Dentales.
        /// </summary>
        internal static string PdfAuthor {
            get {
                return ResourceManager.GetString("PdfAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indices Dentarios.
        /// </summary>
        internal static string PdfHeader {
            get {
                return ResourceManager.GetString("PdfHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haenggi Mediciones Dentales.
        /// </summary>
        internal static string PdfTitle {
            get {
                return ResourceManager.GetString("PdfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 a 24.
        /// </summary>
        internal static string Pont_14To24 {
            get {
                return ResourceManager.GetString("Pont_14To24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 a 26.
        /// </summary>
        internal static string Pont_16To26 {
            get {
                return ResourceManager.GetString("Pont_16To26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitud de Arco.
        /// </summary>
        internal static string Pont_LongArch {
            get {
                return ResourceManager.GetString("Pont_LongArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pont.
        /// </summary>
        internal static string Pont_Title {
            get {
                return ResourceManager.GetString("Pont_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanaka-Johnston (C-Pm-Pm).
        /// </summary>
        internal static string Tanaka_Title {
            get {
                return ResourceManager.GetString("Tanaka_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados Indices Dentarios.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
